#!/bin/sh -e
# Accepted values: postgres, kafka, redis, pulsar
# If no variable provided all services will start
if [ -n "$1" ]; then
    if [ "$1" != "kafka" ] && [ "$1" != "redis" ] && [ "$1" != "postgres" ] && [ "$1" != "pulsar" ]; then
        echo  "Not a valid value. Choose one or none:
    kafka
    redis
    pulsar
    postgres ";
        exit 1;
    fi
fi

docker-compose up $1
